### ISSUE TITLE
Example of updating records

### ISSUE THREAD

**Issue by jayo2005** [Tawasta/odoo-xml-rpc-example#1]
Hi I used your example for Creating a (customer) record  and it worked. I could not get any of the examples from the Odoo documentation to work.  Could you give an example of updating the customer record.

**Comment by jarmokortetjarvi** [comment]
Hi,

You'll just need to call `write`instead of `create` and provide an id or ids.

I added an example in 98fa7cbf8e5a7da3af5a820a72802de4c5923617
