### ISSUE TITLE
Workflow in odoo

### ISSUE THREAD

**Issue by BanderMansour** [Tawasta/odoo-xml-rpc-example#2]
$models->exec_workflow(
    $db, $uid, $password,
    'account.invoice', 'invoice_open',
     $invoice_id); 
http://www.odoo.com/documentation/10.0/api_integration.html

this code is not doing any changes to the odoo invoice workflow where it should change the status form
draft => open

I try but I do not get
 any solution .
 
and

**Comment by jarmokortetjarvi** [comment]
This example is done for Odoo 8.0. That wasn't actually mentioned anywhere, so I changed the default branch to 8.0.

Workflows are deprecated in Odoo 10, so I'd guess `exec_workflow()` won't work either.

You will probably have to call the method `action_invoice_open()` with `execute_kw()`.
See https://www.odoo.com/documentation/10.0/api_integration.html "calling for methods"

**Comment by BanderMansour** [comment]
You are right I did what you said and it's worked now ..
