### ISSUE TITLE
invoice register payment via php ripcord and odoo 10 

### ISSUE THREAD

**Issue by BanderMansour** [Tawasta/odoo-xml-rpc-example#3]
I use ripcord with php as you explained and It works fine but , I don't know how I can register payment for the invoices that created on odoo via rpc ..
can you assist me

**Comment by jarmokortetjarvi** [comment]
Can't really help you with that a lot at the moment, sorry. Posting invoice payment wasn't in the scope of this example. You'll probably want to use `account.payment` model and create a draft payment there, then use it's method `post()`, but this may be a bit tricky.

**Comment by BanderMansour** [comment]
Thank you for replay I will try my best and I will update you .

**Comment by MaksymPundyk** [comment]
@BanderMansour Have you success with resitering payments in odoo v10??

**Comment by BanderMansour** [comment]
> @BanderMansour Have you success with resitering payments in odoo v10??

Yes , I do it @MaksymPundyk and I will share it with you 


`// ============== Create Payment  ===============
$invoice_payment = $models->execute_kw($db, $uid, $password,
 $invoice_payment_model,
    'create',
    array(
        array(
            'invoice_ids'=>$invoice_id[0]['id'], // Reference to the invoice itself
            'amount'=>25.20, // Payment Amount
            'communication'=>$invoice_number[0]['number'], // Invoice Number
            'payment_date'=>date("Y/m/d"), // Date 
            'journal_id' =>6 ,//  Journal
            'partner_id'=>$customer_ids[0], // partner id 
            'partner_type'=>'customer', // partner Type        
            'payment_type'=>'inbound', // payment type   inbound or outbound
            'payment_method_id'=>1, //          
        )
    )
);

// Post the payment
$post=$models->execute_kw(
    $db, $uid, $password,
    $invoice_payment_model,'post'
    ,[$invoice_payment]);`

**Comment by MaksymPundyk** [comment]
@BanderMansour Thank you! It was helpful, also I will share my example creating Payment and Registering invoice payment.



```      
        //Creating payment data.
        $paymentData = [
                "payment_date" => $paymentDate,
                "has_invoices" => True,
                "invoice_ids" => [$odooInvoiceId],
                "amount" => $bill->getAmountTotal(),
                "payment_method_id" => $paymentMethodId,
                "currency_id" => 3,
                "journal_id" => $journalId,
                "partner_type" => 'customer',
                "partner_id" => $vendorId,
                "payment_type" => 'inbound'
            ];

        // Open an invoice to paid
        $invoiceOpen = $this->odooApi->client->runMethod(
            "account.invoice",
            "action_invoice_open",
            [$odooInvoiceId]
        );
        if ($invoiceOpen) {
            // create Payment
            $payment = $this->odooApi->client->create("account.payment", $paymentData);
            // My custom method to check the response.
            $paymentId = $this->odooApi->verifyResponse($payment);

            //after order was opened, we can register an invoice payment
            $payAndReconcile = $this->odooApi->client->runMethod("account.invoice", "pay_and_reconcile", [$odooInvoiceId, $journalId, $bill->getAmountTotal()]);
            if ($payAndReconcile === true) {
                //Set paid status to invoice
                $invoicePaid = $this->odooApi->client->runMethod(
                    "account.invoice",
                    "action_invoice_paid",
                    [$odooInvoiceId]
                );
            }
        }
       ```

**Comment by SendyHartanto** [comment]
@MaksymPundyk Hai Maksym, i am a beginner here.. would you like to give an example from the connection using ripcord to using the query? I use laravel and lumen but php is fine too

**Comment by SendyHartanto** [comment]
Hi @BanderMansour and @MaksymPundyk , Thanks for your code! It was helpful, also i will share my example creating and registering invoice payment in lumen or laravel version with Ripcord (https://packagist.org/packages/darkaonline/ripcord)

`$common = RipcordBase::client("$this->url/xmlrpc/2/common");
       //authentication
        $this->uid = $common->authenticate($this->db, 'your_username', 'yourpassword', []);
        //read invoice data
$dataInvoice = $this->common->client->execute_kw(
            $this->db,
            $this->uid,
            'yourpassword',
            'account.invoice',
            'search_read',
            array(
                array(
                    array('number', '=', 'your_invoice_number'),
                )
            )
        );

        //Creating payment data.
        $paymentData = [
            "payment_date" => date('Y-m-d'),
            "has_invoices" => True,
            "invoice_ids" => [array(4,$dataInvoice[0]['id'])],
            "amount" => $dataInvoice[0]['amount_total_company_signed'],
            "payment_method_id" => 1,
            "currency_id" => 13,
            "journal_id" => 8375,
            "partner_type" => 'customer',
            "partner_id" => $dataInvoice[0]['partner_id'][0],
            "payment_type" => 'inbound',
        ];

        // Open an invoice to paid
        $invoiceOpen = $this->common->client->execute_kw(
            $this->db, 
            $this->uid, 
            'yourpassword',
            "account.invoice",
            "action_invoice_open",
            [$dataInvoice[0]['id']]
        );
        
        //initiate var
        $payAndReconcile = '0';

        if ($invoiceOpen) {
            // create Payment
            $payment = $this->common->client->execute_kw(
                $this->db, 
                $this->uid, 
                'yourpassword',
                'account.payment', 
                'create',
                array(
                    $paymentData
                )
            );
            
            $payAndReconcile = $this->common->client->execute_kw(
                $this->db, 
                $this->uid, 
                'yourpassword',
                "account.payment", 
                "action_validate_invoice_payment", 
                [$payment]
            );
        }`

you can use some method to post your payment like `action_validate_invoice_payment` or `post` in account.payment model or `action_invoice_paid` in account.invoice model.

**Comment by thimsoft** [comment]
hello, i use odoo 8 and the code above doesnt work in what i do:
I want to create an invoice and pass the payment of the invoice but in odoo 8, can someone help me?

**Comment by thimsoft** [comment]
with xmlrpc in php
